catalog:
  "@antfu/eslint-config": ^4.13.2
  "@commitlint/cli": ^19.8.1
  "@commitlint/config-conventional": ^19.8.1
  "@commitlint/types": ^19.8.1
  "@emotion/eslint-plugin": ^11.12.0
  "@emotion/styled": ^11.13.0
  "@eslint/compat": ^1.2.9
  "@eslint-react/eslint-plugin": ^1.49.0
  "@fontsource/inter": ^5.1.0
  "@mui/joy": ^5.0.0-beta.52
  "@tanstack/eslint-plugin-query": ^5.74.7
  "@total-typescript/ts-reset": ^0.6.1
  "@types/fs-extra": ^11.0.4
  "@types/lint-staged": ^13.3.0
  "@types/react": ^19.0.8
  "@types/react-dom": ^19.0.3
  "@vitejs/plugin-react": ^4.5.0
  "@vp-tw/eslint-config": ^0.1.1
  "@vp-tw/tsconfig": ^3.0.0
  babel-plugin-react-compiler: ^19.1.0-rc.2
  commitizen: ^4.3.1
  cspell: ^9.0.2
  es-toolkit: ^1.31.0
  eslint: ^9.27.0
  eslint-config-prettier: ^10.1.5
  eslint-plugin-package-json: ^0.31.0
  eslint-plugin-react-compiler: ^19.1.0-rc.2
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-storybook: ^9.0.1
  fast-glob: ^3.3.3
  fs-extra: ^11.3.0
  husky: ^9.1.7
  jiti: ^2.4.2
  lint-staged: ^16.0.0
  npm-run-all: ^4.1.5
  pathe: ^2.0.3
  postcss-styled-syntax: ^0.7.1
  prettier: ^3.5.3
  react: ^19.0.0
  react-dom: ^19.0.0
  stylelint: ^16.19.1
  stylelint-config-idiomatic-order: ^10.0.0
  stylelint-config-standard: ^38.0.0
  stylelint-prettier: ^5.0.3
  tsx: ^4.19.4
  typescript: ^5.8.3
  vite: npm:rolldown-vite@^6.3.14
  vite-tsconfig-paths: ^5.1.4
  vitest: ^2.1.3
onlyBuiltDependencies:
  - unrs-resolver
packages:
  - packages/*
