catalog:
  "@antfu/eslint-config": ^5.4.1
  "@changesets/cli": ^2.29.8
  "@commitlint/cli": ^20.3.1
  "@commitlint/config-conventional": ^20.3.1
  "@commitlint/types": ^20.3.1
  "@emotion/eslint-plugin": ^11.12.0
  "@emotion/styled": ^11.14.0
  "@eslint/compat": ^1.3.2
  "@eslint-react/eslint-plugin": ^1.53.1
  "@fontsource/inter": ^5.2.5
  "@mui/joy": ^5.0.0-beta.52
  "@mui/utils": ^7.1.0
  "@tanstack/eslint-plugin-query": ^5.91.3
  "@total-typescript/ts-reset": ^0.6.1
  "@types/fs-extra": ^11.0.4
  "@types/lint-staged": ^14.0.0
  "@types/react": ^19.1.6
  "@types/react-dom": ^19.1.5
  "@typescript/native-preview": 7.0.0-dev.20260127.1
  "@vitejs/plugin-react": ^5.1.2
  "@vitest/browser-playwright": ^4.0.18
  "@vp-tw/eslint-config": ^0.2.0
  "@vp-tw/tsconfig": ^3.2.1
  babel-plugin-react-compiler: 19.1.0-rc.3
  commitizen: ^4.3.1
  cspell: ^9.6.2
  es-toolkit: ^1.38.0
  eslint: ^9.36.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-package-json: ^0.56.3
  eslint-plugin-react-compiler: 19.1.0-rc.2
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-storybook: ^9.1.7
  fast-glob: ^3.3.3
  fs-extra: ^11.3.2
  husky: ^9.1.7
  jiti: ^2.6.1
  lint-staged: ^16.2.7
  oxfmt: ^0.27.0
  pathe: ^2.0.3
  playwright: ^1.58.0
  postcss-styled-syntax: ^0.7.1
  react: ^19.1.0
  react-dom: ^19.1.0
  tsdown: ^0.12.5
  tsx: ^4.21.0
  typescript: ^5.9.3
  vite: npm:rolldown-vite@^6.3.21
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.18
  vitest-browser-react: ^2.0.4

catalogMode: strict

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

packages:
  - packages/*

publicHoistPattern:
  - "@tsconfig/*"
